version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-scraper-backend
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - web-scraper-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: mysql:8.0
    container_name: web-scraper-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: web-scraper-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - web-scraper-network

networks:
  web-scraper-network:

volumes:
  mysql-data: